version: "3.8"

services:
  frontend:
    #    container_name: frontend
    build:
      context: ./front-end
      dockerfile: ./docker/Dockerfile
    image: ${REGISTRY_URL}/beatstore-frontend:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [ node.labels.type == instance ] # all non-ci machines are marked with type=instance label
    networks:
      - beatstore
networks:
  beatstore:
    name: beatstore
    driver: overlay