version: "3.8"

services:
  visualiser:
    image: bretfisher/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    networks:
      - beatstore
  nginx:
    image: ${REGISTRY_URL}/beatstore-nginx:latest
    ports:
      - "80:80"
    networks:
      - beatstore
networks:
  beatstore:
    name: beatstore
    driver: overlay