const VALIDATOR_TYPE_REQUIRED = 'REQUIRE';
const VALIDATOR_TYPE_MINLENGTH = 'MINLENGTH';
const VALIDATOR_TYPE_MAXLENGTH = 'MAXLENGTH';
const VALIDATOR_TYPE_MIN = 'MIN';
const VALIDATOR_TYPE_MAX = 'MAX';
const VALIDATOR_TYPE_EMAIL = 'EMAIL';
const VALIDATOR_TYPE_FILE = 'FILE';
const VALIDATOR_TYPE_CHECKED = 'CHECKED';
const VALIDATOR_TYPE_NOT_REQUIRED_BUT_MIN_LENGTH = 'NOT_REQUIRED_BUT_MIN_LENGTH';

export {
  VALIDATOR_TYPE_REQUIRED,
  VALIDATOR_TYPE_MINLENGTH,
  VALIDATOR_TYPE_MAXLENGTH,
  VALIDATOR_TYPE_MIN,
  VALIDATOR_TYPE_MAX,
  VALIDATOR_TYPE_EMAIL,
  VALIDATOR_TYPE_FILE,
  VALIDATOR_TYPE_CHECKED,
  VALIDATOR_TYPE_NOT_REQUIRED_BUT_MIN_LENGTH
};
