const VALIDATOR_TYPE_REQUIRE = 'REQUIRE';
const VALIDATOR_TYPE_MINLENGTH = 'MINLENGTH';
const VALIDATOR_TYPE_MAXLENGTH = 'MAXLENGTH';
const VALIDATOR_TYPE_MIN = 'MIN';
const VALIDATOR_TYPE_MAX = 'MAX';
const VALIDATOR_TYPE_EMAIL = 'EMAIL';
const VALIDATOR_TYPE_FILE = 'FILE';
const VALIDATOR_TYPE_CHECKED = 'CHECKED';

export {
    VALIDATOR_TYPE_REQUIRE,
    VALIDATOR_TYPE_MINLENGTH,
    VALIDATOR_TYPE_MAXLENGTH,
    VALIDATOR_TYPE_MIN,
    VALIDATOR_TYPE_MAX,
    VALIDATOR_TYPE_EMAIL,
    VALIDATOR_TYPE_FILE,
    VALIDATOR_TYPE_CHECKED
};