version: "3.8"

services:
  backend:
    #    container_name: backend
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    image: ${REGISTRY_URL}/beatstore-backend:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [ node.labels.type == instance ] # all non-ci machines are marked with type=instance label
    networks:
      - beatstore
    volumes:
      - beatstore-uploaded-beats:/app/data

volumes:
  beatstore-uploaded-beats:
    name: beatstore-uploaded-beats
