name: Admin Bot CD

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./admin-bot

#  CI:
#  uses: ./.github/workflows/admin-bot-ci.yml

jobs:
  CD:
#    needs: [ CI ]
    environment: admin-bot-production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create proper .env
        uses: shine1594/secrets-to-env-action@v1.6.1
        with:
          secrets_env: production
          secrets: ${{ toJSON(secrets) }}
          file_name_prod: haha.txt

      - name: Check file existence
        run: |
          cd ..
          cat haha.txt

      - name: Building image
        run: |
          docker build . -f docker/Dockerfile -t $REGISTRY_URL:/beatstore-admin-bot:latest



