name: Admin Bot CI

on:
  push:
    paths: [ 'admin-bot/**' ]
  workflow_dispatch: # callable manually
  workflow_call: # callable by other workflows

defaults:
  run:
    working-directory: ./admin-bot

jobs:
  admin-bot-ci-job:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # configure action, pass parameters
        # with:

      - name: Show environment secrets
        run: | 
          echo join(${{ secrets }}, '\n') > .env
          cat .env

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('./admin-bot/yarn.lock') }}

      - name: Install dependencies
        run: yarn ci

      - name: Linting
        run: yarn lint:check

      - name: Testing
        run: yarn test