name: Commons CD

on:
  workflow_dispatch:

jobs:
  CD:
    environment: admin-bot-production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to the remote Docker Swarm
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          DOCKER_HOST: ssh://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_URL }}
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> $HOME/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> $HOME/.ssh/id_rsa.pub
          ssh-keyscan -t rsa ${{ secrets.SSH_URL }} >> $HOME/.ssh/known_hosts

          chmod 0600 $HOME/.ssh/*

          docker stack deploy --with-registry-auth -c docker-compose.stack.yml beatstore
