name: Frontend CD

on:
  workflow_dispatch:



jobs:
  CI:
    uses: ./.github/workflows/frontend-ci.yml

  CD:
    needs: [ CI ]
    environment: frontend-production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          directory: front-end
          envkey_PORT: ${{ secrets.PORT }}
          envkey_SKIP_PREFLIGHT_CHECK: true
          envkey_REACT_APP_BACKEND_ASSET_URL: ${{ secrets.REACT_APP_BACKEND_ASSET_URL }}
          envkey_REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          envkey_REACT_APP_PAYPAL_CLIENT_ID: ${{ secrets.REACT_APP_PAYPAL_CLIENT_ID }}


      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push the image
        uses: whoan/docker-build-with-cache-action@v6
        with:
          image_tag: latest
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          image_name: beatstore-frontend
          context: ./front-end
          dockerfile: docker/Dockerfile

      - name: Deploy to the remote Docker Swarm
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          DOCKER_HOST: ssh://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_URL }}
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> $HOME/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> $HOME/.ssh/id_rsa.pub
          ssh-keyscan -t rsa ${{ secrets.SSH_URL }} >> $HOME/.ssh/known_hosts

          chmod 0600 $HOME/.ssh/*

          docker stack deploy --with-registry-auth -c front-end/docker/docker-compose.stack.yml beatstore
