name: Frontend CI

on:
  push:
    paths: ['front-end/**']
  workflow_dispatch: # callable manually
  workflow_call: # callable by other workflows

defaults:
  run:
    working-directory: ./front-end

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # configure action, pass parameters
        # with:

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('./front-end/yarn.lock') }}

      - name: Install dependencies
        run: yarn ci

      - name: Linting
        run: yarn lint:check

      - name: Testing
        run: yarn test
        env:
          SKIP_PREFLIGHT_CHECK: true
