name: Frontend CD

on:
  workflow_dispatch:

jobs:
  CI:
    uses: ./.github/workflows/frontend-ci.yml
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # configure action, pass parameters
        # with: