name: Continuous Integration

on: push

jobs:
  frontend-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # configure action, pass parameters
        # with:

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd front-end/
          yarn ci

      - name: Linting
        run: | 
          cd front-end/
          yarn lint:check

      - name: Testing
        run: |
          cd front-end/
          yarn test
        
        
        
