version: "3.8"

services:
  admin-bot:
    #    container_name: admin-bot
    build:
      context: ./admin-bot
      dockerfile: ./docker/Dockerfile
    image: ${REGISTRY_URL}/beatstore-admin-bot:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 10
      placement:
        constraints: [ node.labels.type == instance ] # all non-ci machines are marked with type=instance label
    networks:
      - beatstore
networks:
  beatstore:
    name: beatstore
    driver: overlay